name: Selenium E2E test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        run: mvn clean test

      - name: Get allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure_results
          gh_pages: gh_pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history